const state={pack:1,price:69,name:"",age:"",language:"Français",theme:""};const packNames={1:"Little Hero",2:"Super Hero",3:"Hero Gift"};const prices={1:69,2:119,3:159};
const creation=document.getElementById("creation"),bar=document.getElementById("progressBar"),cards=[...document.querySelectorAll(".wizard-card")],labels=[...document.querySelectorAll(".steps-labels span")];let step=1;
function openCreation(pack){state.pack=Number(pack);state.price=prices[state.pack];document.querySelectorAll(".choice").forEach(x=>x.classList.toggle("selected",Number(x.dataset.wizardPack)===state.pack));creation.hidden=false;creation.scrollIntoView({behavior:"smooth",block:"start"});render();}
function render(){cards.forEach((c,i)=>c.hidden=i+1!==step);bar.style.width=(step*25)+"%";labels.forEach((x,i)=>x.classList.toggle("active",i+1===step));}
document.querySelectorAll("[data-pack]").forEach(b=>b.addEventListener("click",()=>openCreation(b.dataset.pack)));
document.querySelectorAll(".navbtn").forEach(b=>b.addEventListener("click",e=>{e.preventDefault();openCreation(1)}));
document.querySelectorAll("[data-wizard-pack]").forEach(b=>b.addEventListener("click",()=>{state.pack=Number(b.dataset.wizardPack);state.price=prices[state.pack];document.querySelectorAll(".choice").forEach(x=>x.classList.toggle("selected",x===b));}));
document.querySelectorAll(".theme-choice-grid button").forEach(b=>b.addEventListener("click",()=>{state.theme=b.dataset.theme;document.querySelectorAll(".theme-choice-grid button").forEach(x=>x.classList.toggle("selected",x===b));}));
document.querySelectorAll(".next").forEach(b=>b.addEventListener("click",()=>{if(step===2){state.name=document.getElementById("childName").value.trim();state.age=document.getElementById("childAge").value;state.language=document.getElementById("language").value;if(!state.name||!state.age){alert("Veuillez renseigner le prénom et l'âge de votre enfant.");return}}if(step===3&&!state.theme){alert("Choisissez une aventure pour continuer.");return}if(step<4)step++;updatePreview();render();}));
document.querySelectorAll(".back").forEach(b=>b.addEventListener("click",()=>{if(step>1)step--;render();}));
function updatePreview(){document.getElementById("summaryName").textContent=state.name||"Votre enfant";document.getElementById("summaryAge").textContent=state.age||"—";document.getElementById("summaryLang").textContent=state.language;document.getElementById("summaryPack").textContent=packNames[state.pack];document.getElementById("summaryPrice").textContent=state.price+" DH";document.getElementById("previewTitle").textContent=state.name?state.name+" et son aventure":"Mon aventure";document.getElementById("previewTheme").textContent=state.theme||"Choisissez un univers";}
render();